### ISSUE TITLE
unable to start session on AppleTV

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#140]
it seems like latest changes with orientation break AppleTV:
```
2023-08-14T18:02:07.531Z INF/wdaClient 23 [bd03d002eae5d3087074198596cec3a0faf72a7d] verifying wda session status...
2023-08-14T18:02:07.704Z VRB/wdaClient 23 [bd03d002eae5d3087074198596cec3a0faf72a7d] Request has been sent to WDA with data:  {"method":"POST","uri":"http://appium:8100/session","body":{"capabilities":{}},"json":true}
2023-08-14T18:02:07.717Z VRB/wdaClient 23 [bd03d002eae5d3087074198596cec3a0faf72a7d] Request has been sent to WDA with data:  {"method":"GET","uri":"http://appium:8100/status","json":true}
2023-08-14T18:02:07.718Z INF/wdaClient 23 [bd03d002eae5d3087074198596cec3a0faf72a7d] status response: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"tvOS","sdkVersion":"16.4","version":"16.4.1"},"ios":{"ip":"169.254.36.211"},"ready":true,"build":{"time":"Aug 14 2023 20:38:12","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"33749013-CFEB-4C6C-8832-DADE1CD678FB"}
2023-08-14T18:02:07.719Z INF/wdaClient 23 [bd03d002eae5d3087074198596cec3a0faf72a7d] reusing existing wda session: 33749013-CFEB-4C6C-8832-DADE1CD678FB
2023-08-14T18:02:07.721Z INF/wdaClient 23 [bd03d002eae5d3087074198596cec3a0faf72a7d] Setting device version: 16.4.1
2023-08-14T18:02:07.723Z INF/wdaClient 23 [bd03d002eae5d3087074198596cec3a0faf72a7d] getting device window size...
2023-08-14T18:02:07.868Z VRB/wdaClient 23 [bd03d002eae5d3087074198596cec3a0faf72a7d] Request has been sent to WDA with data:  {"method":"GET","uri":"http://appium:8100/session/33749013-CFEB-4C6C-8832-DADE1CD678FB/window/size"}
2023-08-14T18:02:07.878Z INF/util:lifecycle 23 [bd03d002eae5d3087074198596cec3a0faf72a7d] Winding down for graceful exit, with optional error :  StatusCodeError: 404 - {"value":{"error":"unknown command","message":"Unhandled endpoint: /session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation -- http://appium:8100/ with parameters {\n    wildcards =     (\n        \"session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation\"\n    );\n}","traceback":""},"sessionId":"33749013-CFEB-4C6C-8832-DADE1CD678FB"}
    at new StatusCodeError (/opt/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/opt/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/opt/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/opt/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/opt/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/opt/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  statusCode: 404,
  error: {
    value: {
      error: 'unknown command',
      message: 'Unhandled endpoint: /session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation -- http://appium:8100/ with parameters {\n' +
        '    wildcards =     (\n' +
        '        "session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation"\n' +
        '    );\n' +
        '}',
      traceback: ''
    },
    sessionId: '33749013-CFEB-4C6C-8832-DADE1CD678FB'
  },
  options: {
    method: 'GET',
    uri: 'http://appium:8100/session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation',
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'appium',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(async_id_symbol)]: 130,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    rawHeaders: [
      'Server',
      'WebDriverAgent/1.0',
      'Content-Type',
      'application/json;charset=UTF-8',
      'Access-Control-Allow-Origin',
      '*',
      'Date',
      'Mon, 14 Aug 2023 18:02:07 GMT',
      'Access-Control-Allow-Headers',
      'Content-Type, X-Requested-With',
      'Accept-Ranges',
      'bytes',
      'Content-Length',
      '381',
      'Connection',
      'close'
    ],
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 404,
    statusMessage: 'Not Found',
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'appium',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(async_id_symbol)]: 130,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation HTTP/1.1\r\n' +
        'host: appium:8100\r\n' +
        'accept: application/json\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'appium',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      method: 'GET',
      uri: [Url],
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function (anonymous)],
      _rp_reject: [Function (anonymous)],
      _rp_promise: [Promise [Object]],
      _rp_callbackOrig: undefined,
      callback: [Function (anonymous)],
      _rp_options: [Object],
      headers: [Object],
      setHeader: [Function (anonymous)],
      hasHeader: [Function (anonymous)],
      getHeader: [Function (anonymous)],
      removeHeader: [Function (anonymous)],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: false,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: '8100',
      host: 'appium',
      path: '/session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation',
      _json: true,
      httpModule: [Object],
      agentClass: [Function],
      agent: [Agent],
      _started: true,
      href: 'http://appium:8100/session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation',
      req: [ClientRequest],
      ntick: true,
      response: [Circular *1],
      originalHost: 'appium:8100',
      originalHostHeaderName: 'host',
      responseContent: [Circular *1],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: {
      value: [Object],
      sessionId: '33749013-CFEB-4C6C-8832-DADE1CD678FB'
    },
    [Symbol(kCapture)]: false,
    [Symbol(kHeaders)]: {
      server: 'WebDriverAgent/1.0',
      'content-type': 'application/json;charset=UTF-8',
      'access-control-allow-origin': '*',
      date: 'Mon, 14 Aug 2023 18:02:07 GMT',
      'access-control-allow-headers': 'Content-Type, X-Requested-With',
      'accept-ranges': 'bytes',
      'content-length': '381',
      connection: 'close'
    },
    [Symbol(kHeadersCount)]: 16,
    [Symbol(kTrailers)]: null,
    [Symbol(kTrailersCount)]: 0,
    [Symbol(RequestTimeout)]: undefined
  }
}
2023-08-14T18:02:07.886Z FTL/util:lifecycle 23 [bd03d002eae5d3087074198596cec3a0faf72a7d] Shutting down due to fatal error with optional error :  StatusCodeError: 404 - {"value":{"error":"unknown command","message":"Unhandled endpoint: /session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation -- http://appium:8100/ with parameters {\n    wildcards =     (\n        \"session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation\"\n    );\n}","traceback":""},"sessionId":"33749013-CFEB-4C6C-8832-DADE1CD678FB"}
    at new StatusCodeError (/opt/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/opt/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/opt/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/opt/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/opt/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/opt/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  statusCode: 404,
  error: {
    value: {
      error: 'unknown command',
      message: 'Unhandled endpoint: /session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation -- http://appium:8100/ with parameters {\n' +
        '    wildcards =     (\n' +
        '        "session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation"\n' +
        '    );\n' +
        '}',
      traceback: ''
    },
    sessionId: '33749013-CFEB-4C6C-8832-DADE1CD678FB'
  },
  options: {
    method: 'GET',
    uri: 'http://appium:8100/session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation',
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'appium',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(async_id_symbol)]: 130,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    rawHeaders: [
      'Server',
      'WebDriverAgent/1.0',
      'Content-Type',
      'application/json;charset=UTF-8',
      'Access-Control-Allow-Origin',
      '*',
      'Date',
      'Mon, 14 Aug 2023 18:02:07 GMT',
      'Access-Control-Allow-Headers',
      'Content-Type, X-Requested-With',
      'Accept-Ranges',
      'bytes',
      'Content-Length',
      '381',
      'Connection',
      'close'
    ],
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 404,
    statusMessage: 'Not Found',
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'appium',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(async_id_symbol)]: 130,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation HTTP/1.1\r\n' +
        'host: appium:8100\r\n' +
        'accept: application/json\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'appium',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      method: 'GET',
      uri: [Url],
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function (anonymous)],
      _rp_reject: [Function (anonymous)],
      _rp_promise: [Promise [Object]],
      _rp_callbackOrig: undefined,
      callback: [Function (anonymous)],
      _rp_options: [Object],
      headers: [Object],
      setHeader: [Function (anonymous)],
      hasHeader: [Function (anonymous)],
      getHeader: [Function (anonymous)],
      removeHeader: [Function (anonymous)],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: false,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: '8100',
      host: 'appium',
      path: '/session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation',
      _json: true,
      httpModule: [Object],
      agentClass: [Function],
      agent: [Agent],
      _started: true,
      href: 'http://appium:8100/session/33749013-CFEB-4C6C-8832-DADE1CD678FB/orientation',
      req: [ClientRequest],
      ntick: true,
      response: [Circular *1],
      originalHost: 'appium:8100',
      originalHostHeaderName: 'host',
      responseContent: [Circular *1],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: {
      value: [Object],
      sessionId: '33749013-CFEB-4C6C-8832-DADE1CD678FB'
    },
    [Symbol(kCapture)]: false,
    [Symbol(kHeaders)]: {
      server: 'WebDriverAgent/1.0',
      'content-type': 'application/json;charset=UTF-8',
      'access-control-allow-origin': '*',
      date: 'Mon, 14 Aug 2023 18:02:07 GMT',
      'access-control-allow-headers': 'Content-Type, X-Requested-With',
      'accept-ranges': 'bytes',
      'content-length': '381',
      connection: 'close'
    },
    [Symbol(kHeadersCount)]: 16,
    [Symbol(kTrailers)]: null,
    [Symbol(kTrailersCount)]: 0,
    [Symbol(RequestTimeout)]: undefined
  }
}
Exit status: 1
```

**Comment by vdelendik** [comment]
we have complete with TODO and remove hardcoded `phone` device type: https://github.com/zebrunner/mcloud-device/blob/bb24cdb314bb5f011f3e71791cab140d4b726ae9/files/start_all.sh#L64

**Comment by vdelendik** [comment]
DEVICETYPE is detected automatically using go `ios info` utility call

**Comment by dhreben** [comment]
fixed
