### ISSUE TITLE
android: return exit code on stf process crash

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#88]
after appium container stop (test appium process kill/crash) stf is crashed automatically with exit code 1.
```
2022-04-21T12:20:49.340Z INF/provider 7 [*] Providing all 1 device(s)
2022-04-21T12:55:08.324Z FTL/util:lifecycle 21 [4d003e5f4aad21e7] Forward shell ended; we shall share its fate
2022-04-21T12:55:08.325Z FTL/util:lifecycle 21 [4d003e5f4aad21e7] Shutting down due to fatal error with optional error :  undefined
2022-04-21T12:55:08.330Z FTL/util:lifecycle 7 [*] Tracker had an error Error: Connection closed
    at /opt/node_modules/@devicefarmer/adbkit/lib/adb/tracker.js:21:13
    at tryCatcher (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/catch_filter.js:40:36)
    at CatchFilter.tryCatcher (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2022-04-21T12:55:08.330Z FTL/util:lifecycle 7 [*] Shutting down due to fatal error with optional error :  undefined
Exit status: 1
```

we have to return the same exit code to be able to restart stf services

**Comment by vdelendik** [comment]
made pretty simple return of status exit code as is. please test that stf is being restarted in case of any problem with:
1. appium process inside appium container
2. appium container itself -> use `docker stop appium-id` 

completion of the feature improvement should be done in scope of #85

**Comment by vdelendik** [comment]
verified together
